// ============================================================================
// Spacia — Streak Dashboard — SINGLE-FILE DEBUG BUNDLE
// ----------------------------------------------------------------------------
// Auto-generated by concatenating the full modular project (types, theme,
// utils, mock data, fake services, hooks, components, screen) into one file
// for quick review / debugging. Local identifier collisions ("styles",
// "delay", "NETWORK_DELAY_MS") were renamed per-section to keep this valid
// in a single module scope. This is NOT the recommended long-term structure
// — split it back into the original multi-file layout for real development.
// ============================================================================

import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Animated, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View, ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { MaterialCommunityIcons } from "@expo/vector-icons";

// ============================================================================
// FILE: types/index.ts
// ============================================================================
// ============================================================================
// Spacia — Streak Dashboard — Shared Types
// ----------------------------------------------------------------------------
// These interfaces describe the shape of data flowing between the (future)
// Flask API and the UI. Every service and hook in this feature is typed
// against these contracts so that swapping mock services for real HTTP
// calls later requires zero changes to components.
// ============================================================================

/** A single folder of flashcards belonging to the user. */
export interface Folder {
  id: string;
  title: string;
  /** Hex color used for the folder icon background / accents. */
  color: string;
  /** MaterialCommunityIcons icon name. */
  icon: string;
  totalCards: number;
  reviewCards: number;
  understoodCards: number;
  /** ISO date string of the last time this folder was studied. */
  lastStudied: string;
}

/** Derived (computed) values for a folder — never stored, always calculated. */
export interface FolderProgress {
  masteryPercent: number;
  remainingCards: number;
  completionPercent: number;
}

/** Today's review goal. */
export interface DailyGoal {
  target: number;
  completed: number;
}

/** Derived values for the daily goal. */
export interface DailyGoalProgress {
  percent: number;
  remaining: number;
  isComplete: boolean;
}

/** A single unlockable/lockable achievement. */
export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  locked: boolean;
  progress: number;
  target: number;
}

/** Streak information for the user. */
export interface StreakInfo {
  currentStreak: number;
  longestStreak: number;
  lastActiveDate: string;
  freezesAvailable: number;
}

/** Aggregate study statistics. */
export interface Statistics {
  cardsReviewed: number;
  gamesPlayed: number;
  studyTimeMinutes: number;
  xpEarned: number;
}

/** Status of a single day in the monthly calendar. */
export type CalendarDayStatus = "completed" | "missed" | "today" | "future" | "inactive";

/** A single day cell in the study calendar. */
export interface CalendarDay {
  date: string; // ISO date (yyyy-mm-dd)
  day: number; // day of month
  status: CalendarDayStatus;
}

/** Today's daily challenge. */
export interface Challenge {
  id: string;
  title: string;
  description: string;
  rewardXP: number;
  completed: boolean;
  progress: number;
  target: number;
}

/** Overall progress snapshot — used where multiple derived stats are needed together. */
export interface UserProgress {
  streak: StreakInfo;
  statistics: Statistics;
  dailyGoal: DailyGoal;
}

/** Generic async resource shape returned by every data hook in this feature. */
export interface AsyncResource<T> {
  data: T | null;
  loading: boolean;
  refreshing: boolean;
  error: string | null;
  refresh: () => Promise<void>;
}

// ============================================================================
// FILE: constants/theme.ts
// ============================================================================
// ============================================================================
// Spacia — Theme Tokens
// Dark, premium, green-accented palette. All components pull colors/spacing
// from here — no hardcoded hex values inside components.
// ============================================================================

export const colors = {
  // Backgrounds
  background: "#0A1410",
  backgroundElevated: "#0F1B16",
  surface: "#132119",
  surfaceElevated: "#1A2A21",
  surfaceHighlight: "#213328",

  // Borders / dividers
  border: "#1E2E25",
  borderLight: "#2A3D31",

  // Brand green accents
  primary: "#34D399",
  primaryDark: "#10B981",
  primaryMuted: "#1F4A38",
  primarySoft: "rgba(52, 211, 153, 0.12)",

  // Secondary accent (mint / lime for highlights)
  accent: "#A7F3D0",

  // Text
  textPrimary: "#F4FBF7",
  textSecondary: "#9AB0A3",
  textTertiary: "#647A6E",
  textInverse: "#06120C",

  // Status colors
  success: "#34D399",
  warning: "#FBBF24",
  danger: "#F87171",
  info: "#60A5FA",

  // Calendar status colors
  calendarCompleted: "#34D399",
  calendarMissed: "#3A2A2A",
  calendarToday: "#FBBF24",
  calendarFuture: "#16221C",

  // Misc
  streakFlame: "#FB923C",
  xpGold: "#FBBF24",
  overlay: "rgba(6, 18, 12, 0.6)",
  white: "#FFFFFF",
  black: "#000000",
};

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
};

export const radii = {
  sm: 10,
  md: 14,
  lg: 18,
  xl: 24,
  pill: 999,
};

export const typography = {
  display: {
    fontSize: 30,
    fontWeight: "800" as const,
    letterSpacing: -0.5,
  },
  h1: {
    fontSize: 22,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  h2: {
    fontSize: 18,
    fontWeight: "700" as const,
  },
  body: {
    fontSize: 15,
    fontWeight: "500" as const,
  },
  bodySmall: {
    fontSize: 13,
    fontWeight: "500" as const,
  },
  caption: {
    fontSize: 12,
    fontWeight: "600" as const,
    letterSpacing: 0.4,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: "700" as const,
    letterSpacing: 1.2,
  },
};

export const shadow = {
  card: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  soft: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
};

// ============================================================================
// FILE: constants/quotes.ts
// ============================================================================
// ============================================================================
// Spacia — Motivational Quotes
// A random quote is selected on mount and on every pull-to-refresh.
// ============================================================================

export const MOTIVATIONAL_QUOTES: string[] = [
  "Small progress every day leads to big results.",
  "Consistency beats intensity. Show up today.",
  "Your future self is built by what you review today.",
  "Every card you learn is a rep for your brain.",
  "Discipline is choosing between what you want now and what you want most.",
  "The streak isn't the goal. The habit is.",
  "You don't have to be perfect, just present.",
  "Progress, not perfection.",
  "A little each day adds up to a lot.",
  "Focus on being 1% better than yesterday.",
];

export function getRandomQuote(excluding?: string): string {
  const pool = excluding
    ? MOTIVATIONAL_QUOTES.filter((q) => q !== excluding)
    : MOTIVATIONAL_QUOTES;
  const index = Math.floor(Math.random() * pool.length);
  return pool[index];
}

// ============================================================================
// FILE: utils/date.ts
// ============================================================================
// ============================================================================
// Spacia — Date Utilities
// ============================================================================

/** Returns YYYY-MM-DD for a given Date, in local time (no timezone shifting). */
export function toISODate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/** Number of days in the given month (0-indexed month, like Date.getMonth()). */
export function daysInMonth(year: number, month: number): number {
  return new Date(year, month + 1, 0).getDate();
}

/** Short weekday label, e.g. "M", "T", "W" — used for calendar column headers. */
export const WEEKDAY_LABELS = ["S", "M", "T", "W", "T", "F", "S"];

/** Human friendly "N days ago" style label — used for folder "last studied". */
export function relativeDayLabel(isoDate: string): string {
  const target = new Date(isoDate);
  const now = new Date();
  const startOfTarget = new Date(target.getFullYear(), target.getMonth(), target.getDate());
  const startOfNow = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const diffMs = startOfNow.getTime() - startOfTarget.getTime();
  const diffDays = Math.round(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays <= 0) return "Today";
  if (diffDays === 1) return "Yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  const weeks = Math.floor(diffDays / 7);
  if (weeks === 1) return "1 week ago";
  return `${weeks} weeks ago`;
}

export function currentMonthLabel(): string {
  return new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
}

// ============================================================================
// FILE: utils/calculations.ts
// ============================================================================
// ============================================================================
// Spacia — Business Logic: Derived Calculations
// Every percentage / remaining-value shown in the UI is computed here from
// raw counts, never hardcoded in a component.
// ============================================================================


/** Clamp a number between 0 and 100 and round to the nearest whole percent. */
export function toPercent(numerator: number, denominator: number): number {
  if (denominator <= 0) return 0;
  const raw = (numerator / denominator) * 100;
  return Math.max(0, Math.min(100, Math.round(raw)));
}

/** Compute mastery %, remaining cards, and completion % for a folder. */
export function computeFolderProgress(folder: Folder): FolderProgress {
  const masteryPercent = toPercent(folder.understoodCards, folder.totalCards);
  const completionPercent = toPercent(folder.reviewCards, folder.totalCards);
  const remainingCards = Math.max(folder.totalCards - folder.reviewCards, 0);

  return { masteryPercent, remainingCards, completionPercent };
}

/** Compute percent complete, cards remaining, and completion flag for today's goal. */
export function computeDailyGoalProgress(goal: DailyGoal): DailyGoalProgress {
  const percent = toPercent(goal.completed, goal.target);
  const remaining = Math.max(goal.target - goal.completed, 0);
  const isComplete = goal.completed >= goal.target;

  return { percent, remaining, isComplete };
}

/** Motivational copy that reacts to actual progress rather than a static string. */
export function dailyGoalMessage(progress: DailyGoalProgress): string {
  if (progress.isComplete) return "Goal complete! Great work today.";
  if (progress.percent >= 75) return "You're almost there!";
  if (progress.percent >= 40) return "Nice pace, keep it going.";
  if (progress.percent > 0) return "You've made a start — keep going.";
  return "Let's get today's reviews started.";
}

/** Achievement progress percent, clamped to target. */
export function achievementProgressPercent(progress: number, target: number): number {
  return toPercent(progress, target);
}

// ============================================================================
// FILE: utils/xp.ts
// ============================================================================
// ============================================================================
// Spacia — XP Rules
// Central place defining how many XP points each action is worth, so the
// value is never duplicated (or guessed) across the app.
// ============================================================================

export const XP_RULES = {
  REVIEW_CARD: 2,
  UNDERSTAND_CARD: 5,
  COMPLETE_CHALLENGE: 100,
  MAINTAIN_STREAK: 20,
} as const;

export function xpForReviewedCards(cardCount: number): number {
  return cardCount * XP_RULES.REVIEW_CARD;
}

export function xpForUnderstoodCards(cardCount: number): number {
  return cardCount * XP_RULES.UNDERSTAND_CARD;
}

export function formatXP(xp: number): string {
  if (xp >= 1000) {
    return `${(xp / 1000).toFixed(1).replace(/\.0$/, "")}k`;
  }
  return `${xp}`;
}

// ============================================================================
// FILE: data/streakData.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Streak
// Shape mirrors what GET /api/streak would return from the Flask backend.
// ============================================================================


export const mockStreakInfo: StreakInfo = {
  currentStreak: 7,
  longestStreak: 21,
  lastActiveDate: toISODate(new Date()),
  freezesAvailable: 2,
};

export const mockDailyGoal: DailyGoal = {
  target: 20,
  completed: 15,
};

// ============================================================================
// FILE: data/statistics.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Statistics
// Shape mirrors what GET /api/statistics would return.
// ============================================================================


export const mockStatistics: Statistics = {
  cardsReviewed: 342,
  gamesPlayed: 18,
  studyTimeMinutes: 465, // displayed as hours/minutes in the UI
  xpEarned: 2140,
};

// ============================================================================
// FILE: data/folders.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Folders
// Shape mirrors what GET /api/folders would return. Mastery, remaining, and
// completion are intentionally NOT stored here — they're derived at render
// time via utils/calculations.ts.
// ============================================================================


export const mockFolders: Folder[] = [
  {
    id: "folder-1",
    title: "Spanish Vocabulary",
    color: "#34D399",
    icon: "translate",
    totalCards: 120,
    reviewCards: 96,
    understoodCards: 84,
    lastStudied: "2026-08-03",
  },
  {
    id: "folder-2",
    title: "Organic Chemistry",
    color: "#60A5FA",
    icon: "flask-outline",
    totalCards: 85,
    reviewCards: 40,
    understoodCards: 22,
    lastStudied: "2026-08-02",
  },
  {
    id: "folder-3",
    title: "World History",
    color: "#FBBF24",
    icon: "book-open-page-variant-outline",
    totalCards: 60,
    reviewCards: 60,
    understoodCards: 55,
    lastStudied: "2026-07-30",
  },
  {
    id: "folder-4",
    title: "Data Structures",
    color: "#F87171",
    icon: "sitemap-outline",
    totalCards: 45,
    reviewCards: 10,
    understoodCards: 4,
    lastStudied: "2026-07-27",
  },
  {
    id: "folder-5",
    title: "Anatomy Basics",
    color: "#A78BFA",
    icon: "heart-pulse",
    totalCards: 96,
    reviewCards: 70,
    understoodCards: 61,
    lastStudied: "2026-07-25",
  },
];

// ============================================================================
// FILE: data/achievements.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Achievements
// Shape mirrors what GET /api/achievements would return. `locked` is stored
// explicitly (a backend business rule may unlock things for reasons beyond
// simple progress >= target), while progress badges are still derived from
// progress/target in the UI layer.
// ============================================================================


export const mockAchievements: Achievement[] = [
  {
    id: "ach-1",
    title: "7 Day Streak",
    description: "Study every day for a full week.",
    icon: "fire",
    locked: false,
    progress: 7,
    target: 7,
  },
  {
    id: "ach-2",
    title: "First Folder",
    description: "Create your first flashcard folder.",
    icon: "folder-star-outline",
    locked: false,
    progress: 1,
    target: 1,
  },
  {
    id: "ach-3",
    title: "AI Explorer",
    description: "Generate flashcards with AI 5 times.",
    icon: "creation",
    locked: false,
    progress: 3,
    target: 5,
  },
  {
    id: "ach-4",
    title: "Flashcard Master",
    description: "Review 500 flashcards total.",
    icon: "cards-outline",
    locked: true,
    progress: 342,
    target: 500,
  },
  {
    id: "ach-5",
    title: "Gamer",
    description: "Play 25 study games.",
    icon: "gamepad-variant-outline",
    locked: true,
    progress: 18,
    target: 25,
  },
  {
    id: "ach-6",
    title: "Night Owl",
    description: "Study after 10pm five times.",
    icon: "weather-night",
    locked: true,
    progress: 1,
    target: 5,
  },
];

// ============================================================================
// FILE: data/calendar.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Study Calendar
// A real backend would return a list of {date, status} entries for the
// current month. Here we generate the current month locally and assign a
// deterministic-but-varied status per day so the calendar always looks
// populated, no matter when this runs.
// ============================================================================


/** Days (by day-of-month) that are treated as "missed" in the mock data. */
const MOCK_MISSED_DAYS = new Set([3, 9, 14, 22]);

export function generateMockCalendar(reference: Date = new Date()): CalendarDay[] {
  const year = reference.getFullYear();
  const month = reference.getMonth();
  const totalDays = daysInMonth(year, month);
  const todayISO = toISODate(reference);
  const days: CalendarDay[] = [];

  for (let day = 1; day <= totalDays; day++) {
    const date = new Date(year, month, day);
    const iso = toISODate(date);

    let status: CalendarDayStatus;
    if (iso === todayISO) {
      status = "today";
    } else if (date > reference) {
      status = "future";
    } else if (MOCK_MISSED_DAYS.has(day)) {
      status = "missed";
    } else {
      status = "completed";
    }

    days.push({ date: iso, day, status });
  }

  return days;
}

export const mockCalendarDays: CalendarDay[] = generateMockCalendar();

// ============================================================================
// FILE: data/dailyChallenge.ts
// ============================================================================
// ============================================================================
// Spacia — Mock Data: Daily Challenge
// Shape mirrors what GET /api/challenge/today would return.
// ============================================================================


export const mockDailyChallenge: Challenge = {
  id: "challenge-2026-08-03",
  title: "Review 30 flashcards",
  description: "Complete 30 flashcard reviews across any folder today.",
  rewardXP: 100,
  completed: false,
  progress: 15,
  target: 30,
};

// ============================================================================
// FILE: services/StreakService.ts
// ============================================================================
// ============================================================================
// Spacia — StreakService
// Mimics `GET /api/streak` and `GET /api/goal/today`. Replace the bodies of
// these methods with `fetch()` calls (using a JWT-authenticated client) when
// the Flask backend is ready — hooks and components will not need to change.
// ============================================================================


const STREAK_NETWORK_DELAY_MS = 300;

function streakDelay<T>(value: T, ms: number = STREAK_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

export const StreakService = {
  /** GET /api/streak */
  async getStreak(): Promise<StreakInfo> {
    return streakDelay({ ...mockStreakInfo });
  },

  /** GET /api/goal/today */
  async getDailyGoal(): Promise<DailyGoal> {
    return streakDelay({ ...mockDailyGoal });
  },
};

// ============================================================================
// FILE: services/StatisticsService.ts
// ============================================================================
// ============================================================================
// Spacia — StatisticsService
// Mimics `GET /api/statistics`.
// ============================================================================


const STATISTICS_NETWORK_DELAY_MS = 350;

function statisticsDelay<T>(value: T, ms: number = STATISTICS_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

export const StatisticsService = {
  /** GET /api/statistics */
  async getStatistics(): Promise<Statistics> {
    return statisticsDelay({ ...mockStatistics });
  },
};

// ============================================================================
// FILE: services/FolderService.ts
// ============================================================================
// ============================================================================
// Spacia — FolderService
// Mimics `GET /api/folders`.
// ============================================================================


const FOLDER_NETWORK_DELAY_MS = 400;

function folderDelay<T>(value: T, ms: number = FOLDER_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

export const FolderService = {
  /** GET /api/folders */
  async getFolders(): Promise<Folder[]> {
    return folderDelay(mockFolders.map((folder) => ({ ...folder })));
  },
};

// ============================================================================
// FILE: services/AchievementService.ts
// ============================================================================
// ============================================================================
// Spacia — AchievementService
// Mimics `GET /api/achievements`.
// ============================================================================


const ACHIEVEMENT_NETWORK_DELAY_MS = 350;

function achievementDelay<T>(value: T, ms: number = ACHIEVEMENT_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

export const AchievementService = {
  /** GET /api/achievements */
  async getAchievements(): Promise<Achievement[]> {
    return achievementDelay(mockAchievements.map((achievement) => ({ ...achievement })));
  },
};

// ============================================================================
// FILE: services/CalendarService.ts
// ============================================================================
// ============================================================================
// Spacia — CalendarService
// Mimics `GET /api/calendar?month=YYYY-MM`.
// ============================================================================


const CALENDAR_NETWORK_DELAY_MS = 300;

function calendarDelay<T>(value: T, ms: number = CALENDAR_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

export const CalendarService = {
  /** GET /api/calendar?month=YYYY-MM */
  async getMonth(reference: Date = new Date()): Promise<CalendarDay[]> {
    return calendarDelay(generateMockCalendar(reference));
  },
};

// ============================================================================
// FILE: services/ChallengeService.ts
// ============================================================================
// ============================================================================
// Spacia — ChallengeService
// Mimics `GET /api/challenge/today` and `POST /api/challenge/:id/start`.
// ============================================================================


const CHALLENGE_NETWORK_DELAY_MS = 300;

function challengeDelay<T>(value: T, ms: number = CHALLENGE_NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

// In-memory copy so "starting" a challenge can mutate state between calls,
// the same way a real backend session would.
let challengeState: Challenge = { ...mockDailyChallenge };

export const ChallengeService = {
  /** GET /api/challenge/today */
  async getTodayChallenge(): Promise<Challenge> {
    return challengeDelay({ ...challengeState });
  },

  /** POST /api/challenge/:id/start — nudges progress forward to simulate starting a session. */
  async startChallenge(id: string): Promise<Challenge> {
    if (challengeState.id === id && !challengeState.completed) {
      const nextProgress = Math.min(
        challengeState.progress + 5,
        challengeState.target
      );
      challengeState = {
        ...challengeState,
        progress: nextProgress,
        completed: nextProgress >= challengeState.target,
      };
    }
    return challengeDelay({ ...challengeState });
  },
};

// ============================================================================
// FILE: hooks/useStreak.ts
// ============================================================================
// ============================================================================
// Spacia — useStreak
// Loads streak info via StreakService. The UI never knows whether this data
// comes from mock services or a real backend.
// ============================================================================


export function useStreak(): AsyncResource<StreakInfo> {
  const [data, setData] = useState<StreakInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await StreakService.getStreak();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load streak.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  return { data, loading, refreshing, error, refresh };
}

// ============================================================================
// FILE: hooks/useDailyGoal.ts
// ============================================================================
// ============================================================================
// Spacia — useDailyGoal
// Loads today's goal via StreakService and exposes derived progress values.
// ============================================================================


interface UseDailyGoalResult extends AsyncResource<DailyGoal> {
  percent: number;
  remaining: number;
  isComplete: boolean;
  message: string;
}

export function useDailyGoal(): UseDailyGoalResult {
  const [data, setData] = useState<DailyGoal | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await StreakService.getDailyGoal();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load daily goal.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  const progress = useMemo(
    () => (data ? computeDailyGoalProgress(data) : { percent: 0, remaining: 0, isComplete: false }),
    [data]
  );

  const message = useMemo(() => dailyGoalMessage(progress), [progress]);

  return { data, loading, refreshing, error, refresh, ...progress, message };
}

// ============================================================================
// FILE: hooks/useStatistics.ts
// ============================================================================
// ============================================================================
// Spacia — useStatistics
// ============================================================================


export function useStatistics(): AsyncResource<Statistics> {
  const [data, setData] = useState<Statistics | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await StatisticsService.getStatistics();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load statistics.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  return { data, loading, refreshing, error, refresh };
}

// ============================================================================
// FILE: hooks/useAchievements.ts
// ============================================================================
// ============================================================================
// Spacia — useAchievements
// ============================================================================


export function useAchievements(): AsyncResource<Achievement[]> {
  const [data, setData] = useState<Achievement[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await AchievementService.getAchievements();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load achievements.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  return { data, loading, refreshing, error, refresh };
}

// ============================================================================
// FILE: hooks/useCalendar.ts
// ============================================================================
// ============================================================================
// Spacia — useCalendar
// ============================================================================


export function useCalendar(): AsyncResource<CalendarDay[]> {
  const [data, setData] = useState<CalendarDay[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await CalendarService.getMonth();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load calendar.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  return { data, loading, refreshing, error, refresh };
}

// ============================================================================
// FILE: hooks/useFolders.ts
// ============================================================================
// ============================================================================
// Spacia — useFolders
// ============================================================================


export function useFolders(): AsyncResource<Folder[]> {
  const [data, setData] = useState<Folder[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await FolderService.getFolders();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load folders.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  return { data, loading, refreshing, error, refresh };
}

// ============================================================================
// FILE: hooks/useDailyChallenge.ts
// ============================================================================
// ============================================================================
// Spacia — useDailyChallenge
// Exposes both the loaded challenge and a `startChallenge()` action, mirroring
// how a real mutation (POST) would be wired once the backend exists.
// ============================================================================


interface UseDailyChallengeResult extends AsyncResource<Challenge> {
  starting: boolean;
  startChallenge: () => Promise<void>;
}

export function useDailyChallenge(): UseDailyChallengeResult {
  const [data, setData] = useState<Challenge | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [starting, setStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (isRefresh: boolean) => {
    try {
      isRefresh ? setRefreshing(true) : setLoading(true);
      setError(null);
      const result = await ChallengeService.getTodayChallenge();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load challenge.");
    } finally {
      isRefresh ? setRefreshing(false) : setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  const refresh = useCallback(async () => {
    await load(true);
  }, [load]);

  const startChallenge = useCallback(async () => {
    if (!data || data.completed) return;
    try {
      setStarting(true);
      const result = await ChallengeService.startChallenge(data.id);
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to start challenge.");
    } finally {
      setStarting(false);
    }
  }, [data]);

  return { data, loading, refreshing, error, refresh, starting, startChallenge };
}

// ============================================================================
// FILE: hooks/useQuote.ts
// ============================================================================
// ============================================================================
// Spacia — useQuote
// Selects a random motivational quote on mount, and a new one every time
// `nextQuote()` is called (used by pull-to-refresh).
// ============================================================================


interface UseQuoteResult {
  quote: string;
  nextQuote: () => void;
}

export function useQuote(): UseQuoteResult {
  const [quote, setQuote] = useState<string>(() => getRandomQuote());

  const nextQuote = useCallback(() => {
    setQuote((current) => getRandomQuote(current));
  }, []);

  return { quote, nextQuote };
}

// ============================================================================
// FILE: components/ProgressBar.tsx
// ============================================================================
interface ProgressBarProps {
  /** 0–100 */
  percent: number;
  height?: number;
  trackColor?: string;
  fillColor?: string;
}

export function ProgressBar({
  percent,
  height = 8,
  trackColor = colors.surfaceHighlight,
  fillColor = colors.primary,
}: ProgressBarProps) {
  const clamped = Math.max(0, Math.min(100, percent));

  return (
    <View style={[progressBarStyles.track, { height, backgroundColor: trackColor, borderRadius: height / 2 }]}>
      <View
        style={[
          progressBarStyles.fill,
          {
            width: `${clamped}%`,
            backgroundColor: fillColor,
            borderRadius: height / 2,
          },
        ]}
      />
    </View>
  );
}

const progressBarStyles = StyleSheet.create({
  track: {
    width: "100%",
    overflow: "hidden",
  },
  fill: {
    height: "100%",
    borderRadius: radii.pill,
  },
});

// ============================================================================
// FILE: components/StreakBadge.tsx
// ============================================================================
interface StreakBadgeProps {
  days: number;
}

export function StreakBadge({ days }: StreakBadgeProps) {
  return (
    <View style={streakBadgeStyles.badge}>
      <MaterialCommunityIcons name="fire" size={20} color={colors.streakFlame} />
      <Text style={streakBadgeStyles.text}>
        {days} Day Streak
      </Text>
    </View>
  );
}

const streakBadgeStyles = StyleSheet.create({
  badge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: spacing.xxs,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radii.pill,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
    ...shadow.soft,
  },
  text: {
    ...typography.bodySmall,
    color: colors.textPrimary,
    fontWeight: "700",
  },
});

// ============================================================================
// FILE: components/Header.tsx
// ============================================================================
interface HeaderProps {
  streakDays: number;
}

export function Header({ streakDays }: HeaderProps) {
  return (
    <View style={headerStyles.container}>
      <Text style={headerStyles.eyebrow}>WELCOME BACK,</Text>
      <Text style={headerStyles.title}>Let's keep learning.</Text>
      <StreakBadge days={streakDays} />
    </View>
  );
}

const headerStyles = StyleSheet.create({
  container: {
    marginBottom: spacing.lg,
  },
  eyebrow: {
    ...typography.eyebrow,
    color: colors.textSecondary,
    marginBottom: spacing.xxs,
  },
  title: {
    ...typography.display,
    color: colors.textPrimary,
  },
});

// ============================================================================
// FILE: components/SkeletonCard.tsx
// ============================================================================
interface SkeletonCardProps {
  height?: number;
  width?: number | `${number}%`;
  borderRadius?: number;
  style?: ViewStyle;
}

/** A simple pulsing skeleton block, used anywhere data is still loading. */
export function SkeletonCard({
  height = 100,
  width = "100%",
  borderRadius = radii.lg,
  style,
}: SkeletonCardProps) {
  const opacity = useRef(new Animated.Value(0.4)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.sequence([
        Animated.timing(opacity, { toValue: 1, duration: 700, useNativeDriver: true }),
        Animated.timing(opacity, { toValue: 0.4, duration: 700, useNativeDriver: true }),
      ])
    );
    loop.start();
    return () => loop.stop();
  }, [opacity]);

  return (
    <Animated.View
      style={[
        skeletonCardStyles.base,
        { height, width, borderRadius, opacity },
        style,
      ]}
    />
  );
}

const skeletonCardStyles = StyleSheet.create({
  base: {
    backgroundColor: colors.surfaceElevated,
  },
});

// ============================================================================
// FILE: components/DailyGoalCard.tsx
// ============================================================================
interface DailyGoalCardProps {
  target: number;
  completed: number;
  percent: number;
  remaining: number;
  isComplete: boolean;
  message: string;
}

export function DailyGoalCard({
  target,
  completed,
  percent,
  remaining,
  isComplete,
  message,
}: DailyGoalCardProps) {
  return (
    <View style={dailyGoalCardStyles.card}>
      <View style={dailyGoalCardStyles.headerRow}>
        <View style={dailyGoalCardStyles.iconWrap}>
          <MaterialCommunityIcons
            name={isComplete ? "check-circle" : "target"}
            size={20}
            color={colors.primary}
          />
        </View>
        <View style={dailyGoalCardStyles.headerText}>
          <Text style={dailyGoalCardStyles.eyebrow}>TODAY'S GOAL</Text>
          <Text style={dailyGoalCardStyles.title}>Review {target} flashcards</Text>
        </View>
        <Text style={dailyGoalCardStyles.percentLabel}>{percent}%</Text>
      </View>

      <ProgressBar percent={percent} height={10} />

      <View style={dailyGoalCardStyles.footerRow}>
        <Text style={dailyGoalCardStyles.progressLabel}>
          {completed} / {target} completed
        </Text>
        {!isComplete && (
          <Text style={dailyGoalCardStyles.remainingLabel}>{remaining} cards left</Text>
        )}
      </View>

      <Text style={dailyGoalCardStyles.message}>{message}</Text>
    </View>
  );
}

const dailyGoalCardStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
    ...shadow.card,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  iconWrap: {
    width: 38,
    height: 38,
    borderRadius: radii.md,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    flex: 1,
  },
  eyebrow: {
    ...typography.eyebrow,
    color: colors.textTertiary,
    marginBottom: 2,
  },
  title: {
    ...typography.h2,
    color: colors.textPrimary,
  },
  percentLabel: {
    ...typography.h1,
    color: colors.primary,
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressLabel: {
    ...typography.bodySmall,
    color: colors.textSecondary,
  },
  remainingLabel: {
    ...typography.bodySmall,
    color: colors.textTertiary,
  },
  message: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "600",
    marginTop: spacing.xxs,
  },
});

// ============================================================================
// FILE: components/StatisticsCard.tsx
// ============================================================================
interface StatisticsCardProps {
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  label: string;
  value: string;
  accentColor?: string;
}

export function StatisticsCard({
  icon,
  label,
  value,
  accentColor = colors.primary,
}: StatisticsCardProps) {
  return (
    <View style={statisticsCardStyles.card}>
      <View style={[statisticsCardStyles.iconWrap, { backgroundColor: `${accentColor}1F` }]}>
        <MaterialCommunityIcons name={icon} size={18} color={accentColor} />
      </View>
      <Text style={statisticsCardStyles.value}>{value}</Text>
      <Text style={statisticsCardStyles.label}>{label}</Text>
    </View>
  );
}

const statisticsCardStyles = StyleSheet.create({
  card: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xxs,
    ...shadow.soft,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: radii.sm,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xxs,
  },
  value: {
    ...typography.h1,
    color: colors.textPrimary,
  },
  label: {
    ...typography.caption,
    color: colors.textTertiary,
    textTransform: "uppercase",
  },
});

// ============================================================================
// FILE: components/CalendarCard.tsx
// ============================================================================
interface CalendarCardProps {
  days: CalendarDay[];
}

const STATUS_STYLE: Record<
  CalendarDay["status"],
  { backgroundColor: string; textColor: string; borderColor?: string }
> = {
  completed: { backgroundColor: colors.calendarCompleted, textColor: colors.textInverse },
  missed: { backgroundColor: colors.calendarMissed, textColor: colors.textTertiary },
  today: { backgroundColor: colors.calendarToday, textColor: colors.textInverse },
  future: { backgroundColor: colors.calendarFuture, textColor: colors.textTertiary },
  inactive: { backgroundColor: "transparent", textColor: colors.textTertiary },
};

export function CalendarCard({ days }: CalendarCardProps) {
  // Pad the front of the grid so day 1 lands on the correct weekday column.
  const firstDate = days.length > 0 ? new Date(days[0].date) : new Date();
  const leadingBlanks = firstDate.getDay();
  const paddedDays: (CalendarDay | null)[] = [
    ...Array(leadingBlanks).fill(null),
    ...days,
  ];

  return (
    <View style={calendarCardStyles.card}>
      <View style={calendarCardStyles.headerRow}>
        <Text style={calendarCardStyles.title}>{currentMonthLabel()}</Text>
      </View>

      <View style={calendarCardStyles.weekdayRow}>
        {WEEKDAY_LABELS.map((label, index) => (
          <Text key={`${label}-${index}`} style={calendarCardStyles.weekdayLabel}>
            {label}
          </Text>
        ))}
      </View>

      <View style={calendarCardStyles.grid}>
        {paddedDays.map((day, index) => {
          if (!day) {
            return <View key={`blank-${index}`} style={calendarCardStyles.cell} />;
          }
          const style = STATUS_STYLE[day.status];
          return (
            <View key={day.date} style={calendarCardStyles.cell}>
              <View
                style={[
                  calendarCardStyles.dayCircle,
                  { backgroundColor: style.backgroundColor },
                  day.status === "future" && calendarCardStyles.dayCircleOutline,
                ]}
              >
                <Text style={[calendarCardStyles.dayLabel, { color: style.textColor }]}>{day.day}</Text>
              </View>
            </View>
          );
        })}
      </View>

      <View style={calendarCardStyles.legendRow}>
        <LegendItem color={colors.calendarCompleted} label="Completed" />
        <LegendItem color={colors.calendarMissed} label="Missed" />
        <LegendItem color={colors.calendarToday} label="Today" />
      </View>
    </View>
  );
}

function LegendItem({ color, label }: { color: string; label: string }) {
  return (
    <View style={calendarCardStyles.legendItem}>
      <MaterialCommunityIcons name="circle" size={8} color={color} />
      <Text style={calendarCardStyles.legendLabel}>{label}</Text>
    </View>
  );
}

const CELL_SIZE = "14.28%"; // 100 / 7 columns

const calendarCardStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    ...shadow.soft,
  },
  headerRow: {
    marginBottom: spacing.sm,
  },
  title: {
    ...typography.h2,
    color: colors.textPrimary,
  },
  weekdayRow: {
    flexDirection: "row",
    marginBottom: spacing.xs,
  },
  weekdayLabel: {
    width: CELL_SIZE,
    textAlign: "center",
    ...typography.caption,
    color: colors.textTertiary,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cell: {
    width: CELL_SIZE,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xxs,
  },
  dayCircle: {
    width: "78%",
    height: "78%",
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCircleOutline: {
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  dayLabel: {
    fontSize: 12,
    fontWeight: "700",
  },
  legendRow: {
    flexDirection: "row",
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
  },
  legendLabel: {
    ...typography.caption,
    color: colors.textTertiary,
    textTransform: "none",
  },
});

// ============================================================================
// FILE: components/AchievementCard.tsx
// ============================================================================
interface AchievementCardProps {
  achievement: Achievement;
}

export function AchievementCard({ achievement }: AchievementCardProps) {
  const percent = achievementProgressPercent(achievement.progress, achievement.target);
  const isUnlocked = !achievement.locked;

  return (
    <View style={[achievementCardStyles.card, isUnlocked ? achievementCardStyles.cardUnlocked : achievementCardStyles.cardLocked]}>
      <View
        style={[
          achievementCardStyles.iconWrap,
          { backgroundColor: isUnlocked ? colors.primarySoft : colors.surfaceHighlight },
        ]}
      >
        <MaterialCommunityIcons
          name={achievement.icon as keyof typeof MaterialCommunityIcons.glyphMap}
          size={22}
          color={isUnlocked ? colors.primary : colors.textTertiary}
        />
        {!isUnlocked && (
          <View style={achievementCardStyles.lockBadge}>
            <MaterialCommunityIcons name="lock" size={10} color={colors.textInverse} />
          </View>
        )}
      </View>

      <Text style={[achievementCardStyles.title, !isUnlocked && achievementCardStyles.titleLocked]} numberOfLines={1}>
        {achievement.title}
      </Text>
      <Text style={achievementCardStyles.description} numberOfLines={2}>
        {achievement.description}
      </Text>

      <View style={achievementCardStyles.progressRow}>
        <ProgressBar
          percent={percent}
          height={6}
          fillColor={isUnlocked ? colors.primary : colors.textTertiary}
        />
        <Text style={achievementCardStyles.progressText}>
          {achievement.progress}/{achievement.target}
        </Text>
      </View>
    </View>
  );
}

const CARD_WIDTH = 168;

const achievementCardStyles = StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing.md,
    gap: spacing.xxs,
    ...shadow.soft,
  },
  cardUnlocked: {
    borderColor: colors.primaryMuted,
  },
  cardLocked: {
    borderColor: colors.border,
    opacity: 0.75,
  },
  iconWrap: {
    width: 42,
    height: 42,
    borderRadius: radii.md,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xs,
  },
  lockBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: radii.pill,
    backgroundColor: colors.textTertiary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  title: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "700",
  },
  titleLocked: {
    color: colors.textSecondary,
  },
  description: {
    ...typography.bodySmall,
    color: colors.textTertiary,
    minHeight: 32,
  },
  progressRow: {
    marginTop: spacing.xxs,
    gap: spacing.xxs,
  },
  progressText: {
    ...typography.caption,
    color: colors.textTertiary,
    textTransform: "none",
  },
});

// ============================================================================
// FILE: components/FolderCard.tsx
// ============================================================================
interface FolderCardProps {
  folder: Folder;
  onPressMenu?: (folder: Folder) => void;
}

export function FolderCard({ folder, onPressMenu }: FolderCardProps) {
  const { masteryPercent } = computeFolderProgress(folder);

  return (
    <View style={folderCardStyles.card}>
      <View style={folderCardStyles.headerRow}>
        <View style={[folderCardStyles.iconWrap, { backgroundColor: `${folder.color}1F` }]}>
          <MaterialCommunityIcons
            name={folder.icon as keyof typeof MaterialCommunityIcons.glyphMap}
            size={20}
            color={folder.color}
          />
        </View>
        <Pressable
          hitSlop={8}
          onPress={() => onPressMenu?.(folder)}
          style={folderCardStyles.menuButton}
        >
          <MaterialCommunityIcons name="dots-vertical" size={18} color={colors.textTertiary} />
        </Pressable>
      </View>

      <Text style={folderCardStyles.title} numberOfLines={1}>
        {folder.title}
      </Text>
      <Text style={folderCardStyles.subtitle}>
        {folder.totalCards} cards · {relativeDayLabel(folder.lastStudied)}
      </Text>

      <View style={folderCardStyles.progressRow}>
        <ProgressBar percent={masteryPercent} height={6} fillColor={folder.color} />
        <Text style={folderCardStyles.masteryLabel}>{masteryPercent}% mastered</Text>
      </View>
    </View>
  );
}

const folderCardStyles = StyleSheet.create({
  card: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xxs,
    ...shadow.soft,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: radii.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  menuButton: {
    padding: spacing.xxs,
  },
  title: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "700",
    marginTop: spacing.xxs,
  },
  subtitle: {
    ...typography.caption,
    color: colors.textTertiary,
    textTransform: "none",
    marginBottom: spacing.xs,
  },
  progressRow: {
    gap: spacing.xxs,
  },
  masteryLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    textTransform: "none",
  },
});

// ============================================================================
// FILE: components/ChallengeCard.tsx
// ============================================================================
interface ChallengeCardProps {
  challenge: Challenge;
  starting: boolean;
  onStart: () => void;
}

export function ChallengeCard({ challenge, starting, onStart }: ChallengeCardProps) {
  return (
    <View style={challengeCardStyles.card}>
      <View style={challengeCardStyles.topRow}>
        <View style={challengeCardStyles.iconWrap}>
          <MaterialCommunityIcons name="sword-cross" size={20} color={colors.xpGold} />
        </View>
        <View style={challengeCardStyles.rewardPill}>
          <MaterialCommunityIcons name="star-four-points" size={12} color={colors.xpGold} />
          <Text style={challengeCardStyles.rewardText}>{challenge.rewardXP} XP</Text>
        </View>
      </View>

      <Text style={challengeCardStyles.title}>{challenge.title}</Text>
      <Text style={challengeCardStyles.description}>{challenge.description}</Text>

      <Text style={challengeCardStyles.progressText}>
        {challenge.progress}/{challenge.target} completed
      </Text>

      <Pressable
        onPress={onStart}
        disabled={challenge.completed || starting}
        style={({ pressed }) => [
          challengeCardStyles.button,
          challenge.completed && challengeCardStyles.buttonCompleted,
          pressed && !challenge.completed && challengeCardStyles.buttonPressed,
        ]}
      >
        {starting ? (
          <ActivityIndicator color={colors.textInverse} size="small" />
        ) : (
          <>
            <MaterialCommunityIcons
              name={challenge.completed ? "check-bold" : "play"}
              size={16}
              color={colors.textInverse}
            />
            <Text style={challengeCardStyles.buttonText}>
              {challenge.completed ? "Challenge Complete" : "Start Challenge"}
            </Text>
          </>
        )}
      </Pressable>
    </View>
  );
}

const challengeCardStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.xs,
    ...shadow.card,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconWrap: {
    width: 38,
    height: 38,
    borderRadius: radii.md,
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  rewardPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderRadius: radii.pill,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
  },
  rewardText: {
    ...typography.caption,
    color: colors.xpGold,
    textTransform: "none",
  },
  title: {
    ...typography.h2,
    color: colors.textPrimary,
    marginTop: spacing.xs,
  },
  description: {
    ...typography.bodySmall,
    color: colors.textSecondary,
  },
  progressText: {
    ...typography.caption,
    color: colors.textTertiary,
    textTransform: "none",
    marginTop: spacing.xxs,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    backgroundColor: colors.primary,
    borderRadius: radii.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.sm,
  },
  buttonCompleted: {
    backgroundColor: colors.primaryMuted,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  buttonText: {
    ...typography.body,
    color: colors.textInverse,
    fontWeight: "700",
  },
});

// ============================================================================
// FILE: components/QuoteCard.tsx
// ============================================================================
interface QuoteCardProps {
  quote: string;
}

export function QuoteCard({ quote }: QuoteCardProps) {
  return (
    <View style={quoteCardStyles.card}>
      <MaterialCommunityIcons name="format-quote-open" size={22} color={colors.primary} />
      <Text style={quoteCardStyles.quote}>{quote}</Text>
    </View>
  );
}

const quoteCardStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.primarySoft,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    padding: spacing.lg,
    gap: spacing.xs,
  },
  quote: {
    ...typography.body,
    color: colors.textPrimary,
    fontStyle: "italic",
    lineHeight: 21,
  },
});

// ============================================================================
// FILE: components/SectionHeader.tsx
// ============================================================================
interface SectionHeaderProps {
  title: string;
  actionLabel?: string;
  onPressAction?: () => void;
}

export function SectionHeader({ title, actionLabel, onPressAction }: SectionHeaderProps) {
  return (
    <View style={sectionHeaderStyles.row}>
      <Text style={sectionHeaderStyles.title}>{title}</Text>
      {actionLabel && (
        <Text style={sectionHeaderStyles.action} onPress={onPressAction}>
          {actionLabel}
        </Text>
      )}
    </View>
  );
}

const sectionHeaderStyles = StyleSheet.create({
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  title: {
    ...typography.h1,
    color: colors.textPrimary,
  },
  action: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: "700",
  },
});

// ============================================================================
// FILE: screens/StreakDashboardScreen.tsx
// ============================================================================
/** Formats minutes as e.g. "7h 45m" or "45m" for the Study Time stat card. */
function formatStudyTime(minutes: number): string {
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours === 0) return `${mins}m`;
  return `${hours}h ${mins}m`;
}

export function StreakDashboardScreen() {
  const streak = useStreak();
  const dailyGoal = useDailyGoal();
  const statistics = useStatistics();
  const calendar = useCalendar();
  const achievements = useAchievements();
  const folders = useFolders();
  const challenge = useDailyChallenge();
  const { quote, nextQuote } = useQuote();

  const [manualRefreshing, setManualRefreshing] = useState(false);

  const isAnyRefreshing =
    manualRefreshing ||
    streak.refreshing ||
    dailyGoal.refreshing ||
    statistics.refreshing ||
    calendar.refreshing ||
    achievements.refreshing ||
    folders.refreshing ||
    challenge.refreshing;

  const handleRefresh = useCallback(async () => {
    setManualRefreshing(true);
    nextQuote();
    await Promise.all([
      streak.refresh(),
      dailyGoal.refresh(),
      statistics.refresh(),
      calendar.refresh(),
      achievements.refresh(),
      folders.refresh(),
      challenge.refresh(),
    ]);
    setManualRefreshing(false);
  }, [
    achievements,
    calendar,
    challenge,
    dailyGoal,
    folders,
    nextQuote,
    statistics,
    streak,
  ]);

  return (
    <SafeAreaView style={screenStyles.safeArea} edges={["top", "left", "right"]}>
      <ScrollView
        contentContainerStyle={screenStyles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={isAnyRefreshing}
            onRefresh={handleRefresh}
            tintColor={colors.primary}
            colors={[colors.primary]}
          />
        }
      >
        {/* 1. Greeting */}
        <Header streakDays={streak.data?.currentStreak ?? 0} />

        {/* 2. Daily Goal */}
        <View style={screenStyles.sectionSpacing}>
          {dailyGoal.loading ? (
            <SkeletonCard height={160} />
          ) : (
            dailyGoal.data && (
              <DailyGoalCard
                target={dailyGoal.data.target}
                completed={dailyGoal.data.completed}
                percent={dailyGoal.percent}
                remaining={dailyGoal.remaining}
                isComplete={dailyGoal.isComplete}
                message={dailyGoal.message}
              />
            )
          )}
        </View>

        {/* 3. Statistics */}
        <View style={screenStyles.sectionSpacing}>
          <SectionHeader title="Statistics" />
          {statistics.loading ? (
            <View style={screenStyles.statsGrid}>
              <SkeletonCard height={92} width="48%" />
              <SkeletonCard height={92} width="48%" />
              <SkeletonCard height={92} width="48%" />
              <SkeletonCard height={92} width="48%" />
            </View>
          ) : (
            statistics.data && (
              <View style={screenStyles.statsGrid}>
                <StatisticsCard
                  icon="cards-outline"
                  label="Cards Reviewed"
                  value={statistics.data.cardsReviewed.toLocaleString()}
                  accentColor={colors.primary}
                />
                <StatisticsCard
                  icon="gamepad-variant-outline"
                  label="Games Played"
                  value={`${statistics.data.gamesPlayed}`}
                  accentColor={colors.info}
                />
                <StatisticsCard
                  icon="clock-outline"
                  label="Study Time"
                  value={formatStudyTime(statistics.data.studyTimeMinutes)}
                  accentColor={colors.accent}
                />
                <StatisticsCard
                  icon="star-four-points-outline"
                  label="XP Earned"
                  value={formatXP(statistics.data.xpEarned)}
                  accentColor={colors.xpGold}
                />
              </View>
            )
          )}
        </View>

        {/* 4. Study Calendar */}
        <View style={screenStyles.sectionSpacing}>
          <SectionHeader title="Study Calendar" />
          {calendar.loading ? (
            <SkeletonCard height={280} />
          ) : (
            calendar.data && <CalendarCard days={calendar.data} />
          )}
        </View>

        {/* 5. Achievements */}
        <View style={screenStyles.sectionSpacing}>
          <SectionHeader title="Achievements" />
          {achievements.loading ? (
            <View style={screenStyles.achievementsRow}>
              <SkeletonCard height={150} width={168} />
              <SkeletonCard height={150} width={168} />
              <SkeletonCard height={150} width={168} />
            </View>
          ) : (
            achievements.data && (
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={screenStyles.achievementsRow}
              >
                {achievements.data.map((achievement) => (
                  <AchievementCard key={achievement.id} achievement={achievement} />
                ))}
              </ScrollView>
            )
          )}
        </View>

        {/* 6. Continue Studying */}
        <View style={screenStyles.sectionSpacing}>
          <SectionHeader title="Continue Studying" />
          {folders.loading ? (
            <View style={screenStyles.foldersGrid}>
              <SkeletonCard height={140} width="48%" />
              <SkeletonCard height={140} width="48%" />
              <SkeletonCard height={140} width="48%" />
              <SkeletonCard height={140} width="48%" />
            </View>
          ) : (
            folders.data && (
              <View style={screenStyles.foldersGrid}>
                {folders.data.map((folder) => (
                  <FolderCard key={folder.id} folder={folder} />
                ))}
              </View>
            )
          )}
        </View>

        {/* 7. Daily Challenge */}
        <View style={screenStyles.sectionSpacing}>
          <SectionHeader title="Daily Challenge" />
          {challenge.loading ? (
            <SkeletonCard height={190} />
          ) : (
            challenge.data && (
              <ChallengeCard
                challenge={challenge.data}
                starting={challenge.starting}
                onStart={challenge.startChallenge}
              />
            )
          )}
        </View>

        {/* 8. Motivational Quote */}
        <View style={screenStyles.sectionSpacing}>
          <QuoteCard quote={quote} />
        </View>

        {/* Extra bottom padding so content clears the tab bar */}
        <View style={screenStyles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const screenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  sectionSpacing: {
    marginBottom: spacing.xl,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  achievementsRow: {
    gap: spacing.sm,
    paddingRight: spacing.lg,
  },
  foldersGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  bottomSpacer: {
    height: 96,
  },
});

// ============================================================================
// FILE: app/streak-dashboard.tsx (Expo Router route entry)
// ============================================================================
export default function StreakDashboardRoute() {
  return <StreakDashboardScreen />;
}