"""Business operations for manually managed flashcards."""

from extensions import db
from errors import ApiError, NotFoundError
from models.folders import Folder
from models.flashcard import Flashcard


class FlashcardService:
    """
    This service handles all database actions for flashcards.
    Routes/endpoints should talk to this service rather than running direct database queries.
    """
    # We only allow flashcards to have one of these two study states
    VALID_STATUSES = {"review", "understood"}

    def create(self, folder_id: str, user_id: str, question: str, answer: str, status: str, flashcard_id: str | None = None) -> Flashcard:
            """
            Creates a new flashcard manually:
                1. Validates that the status state is valid (either 'review' or 'understood').
                2. Sanitizes input text (removes trailing/leading spaces).
                3. Saves it to the database.
            """
            self._validate_status(status)
            self._get_owned_folder(folder_id, user_id)
            flashcard = Flashcard(
                id=flashcard_id,
                folder_id=folder_id,
                question=question.strip(),
                answer=answer.strip(),
                status=status,
            )
            db.session.add(flashcard)
            db.session.commit()
            return flashcard

    def list_for_folder(self, folder_id: str, user_id: str) -> list[Flashcard]:
        """
        Returns all flashcards inside a specific folder, sorted by their creation date.
        Sorting keeps the list stable and prevents cards from randomly shifting positions.
        """
        self._get_owned_folder(folder_id, user_id)
        return Flashcard.query.filter_by(folder_id=folder_id).order_by(Flashcard.created_at).all()

    def update_status(self, flashcard_id: str, user_id: str, status: str) -> Flashcard:
        """
        Changes the status of a card (e.g. marking it 'understood' once the user studies it).
        If the card ID does not exist, it stops early and raises a 404 error.
        """
        self._validate_status(status)
        flashcard = self._get_owned_or_raise(flashcard_id, user_id)
        flashcard.status = status
        db.session.commit()
        return flashcard

    def update_status_batch(self, user_id: str, updates: list[dict]) -> list[Flashcard]:
        """
        Updates the study status of many flashcards in ONE transaction —
        used by the Quizzy game to sync an entire quiz's worth of answers
        in a single request/commit instead of one PATCH (and one commit)
        per card.

        `updates` is a list of {"id": <flashcard_id>, "status": <status>}
        dicts. All-or-nothing: if any card doesn't exist or isn't owned by
        this user, the whole batch is rejected before anything commits —
        same failure behavior as the single-card `update_status`.
        """
        flashcards = []
        for update in updates:
            status = update["status"]
            self._validate_status(status)
            flashcard = self._get_owned_or_raise(update["id"], user_id)
            flashcard.status = status
            flashcards.append(flashcard)

            # One commit for the whole batch, same pattern as save_generated_cards'
            # batch insert below.
            db.session.commit()
            return flashcards

    def delete(self, flashcard_id: str, user_id: str) -> None:
        """
        Deletes a single flashcard from the database by its ID.
        """
        db.session.delete(self._get_owned_or_raise(flashcard_id, user_id))
        db.session.commit()

    def delete_for_folder(self, folder_id: str, user_id: str) -> int:
        """
        Deletes all flashcards inside a specific folder.
        Returns the number of cards that were deleted.
        """
        self._get_owned_folder(folder_id, user_id)
        deleted_count = Flashcard.query.filter_by(folder_id=folder_id).delete()
        db.session.commit()
        return deleted_count

    def save_generated_cards(self, folder_id: str, user_id: str, cards: list[dict]) -> list[Flashcard]:
        """
        Takes a list of dictionary cards generated by our AI and saves them
        together in a single database transaction. Doing this in one batch
        is much faster than saving them one-by-one.
        """
        self._get_owned_folder(folder_id, user_id)
        # Convert dictionary data into SQLAlchemy database models
        flashcards = [
            Flashcard(
                folder_id=folder_id,
                question=card["question"].strip(),
                answer=card["answer"].strip(),
                status=card.get("status", "review"),
            )
            for card in cards
        ]

        # Double check all of them have valid statuses before committing
        for flashcard in flashcards:
            self._validate_status(flashcard.status)

            # Batch insert all of them
            db.session.add_all(flashcards)
            db.session.commit()
            return flashcards

    @staticmethod
    def _validate_status(status: str) -> None:
        """
        Safety check: checks if the status is allowed.
        If not, it raises a ValueError to prevent bad data from corrupting the database.
        """
        if status not in FlashcardService.VALID_STATUSES:
            allowed = ", ".join(sorted(FlashcardService.VALID_STATUSES))
            raise ValueError(f"Status must be one of: {allowed}.")

    @staticmethod
    def _get_or_raise(flashcard_id: str) -> Flashcard:
        """
        Helper method to find a card by its ID.
        If it cannot find it, it raises a NotFoundError which our API error handler
        converts into a clean JSON 404 response.
        """
        flashcard = db.session.get(Flashcard, flashcard_id)
        if flashcard is None:
            raise NotFoundError("Flashcard")
        return flashcard

    def _get_owned_or_raise(self, flashcard_id: str, user_id: str) -> Flashcard:
        flashcard = self._get_or_raise(flashcard_id)
        self._get_owned_folder(flashcard.folder_id, user_id)
        return flashcard

    @staticmethod
    def _get_owned_folder(folder_id: str, user_id: str) -> Folder:
        folder = db.session.get(Folder, folder_id)
        if folder is None:
            raise NotFoundError("Folder")
        if folder.user_id != user_id:
            raise ApiError("You do not have permission to access this folder.", 403)
        return folder