"""Business operations for manually managed flashcards."""

from extensions import db
from errors import NotFoundError
from models.flashcard import Flashcard


class FlashcardService:
    """
    This service handles all database actions for flashcards.
    Routes/endpoints should talk to this service rather than running direct database queries.
    """
    # We only allow flashcards to have one of these two study states
    VALID_STATUSES = {"review", "understood"}

    def create(self, folder_id: str, question: str, answer: str, status: str, flashcard_id: str | None = None) -> Flashcard:
        """
        Creates a new flashcard manually:
        1. Validates that the status state is valid (either 'review' or 'understood').
        2. Sanitizes input text (removes trailing/leading spaces).
        3. Saves it to the database.
        """
        self._validate_status(status)
        flashcard = Flashcard(
            id=flashcard_id,
            folder_id=folder_id,
            question=question.strip(),
            answer=answer.strip(),
            status=status,
        )
        db.session.add(flashcard)
        db.session.commit()
        return flashcard

    def list_for_folder(self, folder_id: str) -> list[Flashcard]:
        """
        Returns all flashcards inside a specific folder, sorted by their creation date.
        Sorting keeps the list stable and prevents cards from randomly shifting positions.
        """
        return Flashcard.query.filter_by(folder_id=folder_id).order_by(Flashcard.created_at).all()

    def update_status(self, flashcard_id: str, status: str) -> Flashcard:
        """
        Changes the status of a card (e.g. marking it 'understood' once the user studies it).
        If the card ID does not exist, it stops early and raises a 404 error.
        """
        self._validate_status(status)
        flashcard = self._get_or_raise(flashcard_id)
        flashcard.status = status
        db.session.commit()
        return flashcard

    def delete(self, flashcard_id: str) -> None:
        """
        Deletes a single flashcard from the database by its ID.
        """
        db.session.delete(self._get_or_raise(flashcard_id))
        db.session.commit()

    def delete_for_folder(self, folder_id: str) -> int:
        """
        Deletes all flashcards inside a specific folder. 
        Returns the number of cards that were deleted.
        """
        deleted_count = Flashcard.query.filter_by(folder_id=folder_id).delete()
        db.session.commit()
        return deleted_count

    def save_generated_cards(self, folder_id: str, cards: list[dict]) -> list[Flashcard]:
        """
        Takes a list of dictionary cards generated by our AI and saves them 
        together in a single database transaction. Doing this in one batch 
        is much faster than saving them one-by-one.
        """
        # Convert dictionary data into SQLAlchemy database models
        flashcards = [
            Flashcard(
                folder_id=folder_id,
                question=card["question"].strip(),
                answer=card["answer"].strip(),
                status=card.get("status", "review"),
            )
            for card in cards
        ]
        
        # Double check all of them have valid statuses before committing
        for flashcard in flashcards:
            self._validate_status(flashcard.status)

        # Batch insert all of them
        db.session.add_all(flashcards)
        db.session.commit()
        return flashcards

    @staticmethod
    def _validate_status(status: str) -> None:
        """
        Safety check: checks if the status is allowed.
        If not, it raises a ValueError to prevent bad data from corrupting the database.
        """
        if status not in FlashcardService.VALID_STATUSES:
            allowed = ", ".join(sorted(FlashcardService.VALID_STATUSES))
            raise ValueError(f"Status must be one of: {allowed}.")

    @staticmethod
    def _get_or_raise(flashcard_id: str) -> Flashcard:
        """
        Helper method to find a card by its ID.
        If it cannot find it, it raises a NotFoundError which our API error handler
        converts into a clean JSON 404 response.
        """
        flashcard = db.session.get(Flashcard, flashcard_id)
        if flashcard is None:
            raise NotFoundError("Flashcard")
        return flashcard
